name: "Purge Cache Camo"
author: "Angrido"
description: "Clears cached badge images in the README by purging camo.githubusercontent.com."
branding:
  icon: "refresh-cw"
  color: "green"

inputs:
  token:
    description: 'GitHub token for private repositories. Defaults to the token of the repo this action is running in.'
    required: false
    default: '${{ github.token }}'

runs:
  using: "composite"
  steps:

    - name: Get Current Branch
      id: branch-name
      uses: tj-actions/branch-names@v8.2.1

    - name: Purge Cached Camo
      shell: bash
      run: |
        urls=$(curl -sLkH "Authorization: token ${{ inputs.token }}" https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/tree/${{ steps.branch-name.outputs.current_branch }} | grep -Eo "(http|https)://camo.githubusercontent.com[a-zA-Z0-9./?=_%:-]*")

        while IFS= read -r line; do
          curl -X PURGE "$line"
        done <<< "$urls"
