name: "Purge Cache Camo"
author: "Angrido"
description: "Clears cached badge images in the README by purging camo.githubusercontent.com."
branding:
  icon: "refresh-cw"
  color: "green"

runs:
  using: "composite"
  steps:

    - name: Get Current Branch
      id: branch-name
      uses: tj-actions/branch-names@v8.2.1

    - name: Purge Cached Camo Images from README
      shell: bash
      run: |
        raw_url="https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ steps.branch-name.outputs.current_branch }}/README.md"
        urls=$(curl -s "$raw_url" | grep -Eo "https://camo.githubusercontent.com/[a-zA-Z0-9./?=_%-]*")

        echo "Found $(echo \"$urls\" | wc -l) camo URLs."

        while IFS= read -r url; do
          echo "Fetching: $url"
          curl -s -H 'Cache-Control: no-cache' "$url" > /dev/null || echo "Failed: $url"
        done <<< "$urls"
