name: Count Action Users

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  count:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate user count JSON endpoint
        uses: cicirello/count-action-users@v1.0.9
        with:
          action-list: Angrido/Purge-Camo-Cache
          color: 2088FF
          named-logo: githubactions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
